# Generated by Django 5.2.4 on 2025-08-06 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled Date & Time')),
                ('status', models.CharField(choices=[('Canceled', 'Canceled'), ('Scheled', 'Scheduled'), ('Completed', 'Completed')], max_length=9, verbose_name='Scheduling Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='professionals.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'beauty_appointments',
                'ordering': ['scheduled_at', 'client', 'professional'],
                'abstract': False,
                'unique_together': {('client', 'scheduled_at')},
            },
        ),
    ]
